theme = "catppuccin_mocha"

[editor]
line-number = "relative"
auto-pairs = true
shell = ["zsh","-c"]
bufferline = "always"
auto-format=true
preview-completion-insert=false
completion-replace=false
[keys.normal]
C-p = ["move_line_up","scroll_up"]
C-n = ["move_line_down","scroll_down"]
esc = ["collapse_selection","keep_primary_selection"]
C-w = [":buffer-close!"]
C-s = [":write!"]
A-s = [":write-all!"]
C-right = [":buffer-next"]
C-left = [":buffer-previous"]
C-q = [":quit"]
A-q = [":quit!"]

[keys.insert]
C-s = [":write!"]
A-s = [":write-all!"]
C-c = [":clipboard-yank"]
C-v = [":clipboard-paste-after"]
C-right = [":buffer-next"]
C-left = [":buffer-previous"]
C-q = [":quit"]
A-q = [":quit!"]
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints=true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

# [editor.whitespace]
# render = "all"

# [editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# tab = "→"
# newline = "⏎"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)

