theme = "catppuccin_mocha"

[editor]
line-number = "relative"
auto-pairs = true
shell = ["fish","-c"]
bufferline = "multiple"
completion-replace=true
end-of-line-diagnostics = "hint"
[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "error"
[keys.normal]
C-p = ["move_line_up","scroll_up"]
C-n = ["move_line_down","scroll_down"]
esc = ["collapse_selection","keep_primary_selection"]
C-w = [":buffer-close!"]
C-s = [":write!"]
A-s = [":write-all!"]
C-right = [":buffer-next"]
C-left = [":buffer-previous"]
C-q = [":quit"]
A-q = [":quit!"]
[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
[keys.insert]
C-s = [":write!"]
A-s = [":write-all!"]
C-c = [":clipboard-yank"]
C-v = [":clipboard-paste-after"]
C-right = [":buffer-next"]
C-left = [":buffer-previous"]
C-q = [":quit"]
A-q = [":quit!"]
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints=false


[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
# nbsp = "⍽"
 tab = "|"
newline = "⏎"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)

