#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 10
bspc monitor DP1 -d 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          10
bspc config click_to_focus  true
bspc config focused_border_color  "#009fee"
bspc config presel_feedback_color  "#009fee"
bspc config normal_border_color  "#313738"
bspc config focus_by_distance  true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave desktop='^2' state=fullscreen follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# AutoStart
# Top Bar
#~/.config/polybar/grayblocks/launch.sh &
$HOME/.config/polybar/bspwm.sh &
# Picom Window Animation,Blur and Rounded Corner
picom --experimental-backends &
# Wallpaper
feh --bg-fill ~/Pictures/wallpaper.jpg &
dunst &
